### ISSUE TITLE
Using PXC release as a service broker with CF

### ISSUE THREAD

**Issue by crsimmons** [cloudfoundry/pxc-release#10]
# Feature Request Info
## Problem you are trying to solve
The cf-mysql-release includes jobs for setting up and running a service broker on CF. This release seems to be missing those jobs. Is it on your radar to allow this use-case? Ideally we would like to deploy PXC on a separate BOSH director from the one deploying cf-deployment.

## Proposed solution/feature
Probably porting the broker stuff over from cf-mysql-release.

## Would you want to open an PR for this feature?
We're taking a look at porting the broker jobs over from cf-mysql-release but we'd be interested to know if there's already broker work going on or if using this release as a broker isn't a use-case you intend for this release.

**Comment by abg** [comment]
We obviously never ported the broker jobs from cf-mysql-release.   Ideally any broker functionality would be part of a separate bosh release that could incorporate pxc-release, but we do not currently have any plans to support a broker at this time.
