### ISSUE TITLE
False `insufficient disk space` error for disks which have less used space than an empty DB file

### ISSUE THREAD

**Issue by torbencarstens** [cloudfoundry/pxc-release#14]
# Bug Report Info
## Currently:

Our pxc-migration failed due to:

`Cannot continue, insufficient disk space to complete migration.`

Our volume had used ~1.1GB/~19GB which should be sufficient since it's larger than an empty DB.
[This calculation](https://github.com/cloudfoundry-incubator/pxc-release/blob/master/src/migrate-to-pxc/disk/disk.go#L24) doesn't account for `usedKBytes` values which are smaller than `emptyDBSizeKBytes` (2.5GB).

## Expected:
Don't fail the migration if it has enough disk space.

Account for `usedKBytes` values which are smaller than `emptyDBSizeKBytes`, e.g. calculate insufficient disk space via `totalKBytes - usedKBytes > emptyDBSizeKBytes`.

We created an empty 3GB file to ensure that we have used more space than 2.5GB.

## Steps to Reproduce:
Create a volume with less than 2.5 GB and perform the upgrade on there.

## Deployment Context:
Not relevant

## Reference:
`Cannot continue, insufficient disk space to complete migration.`

**Comment by abg** [comment]
Ideally we would have adjusted this calculation in the past, but now I am going to mark this as "will not fix" and close this issue.

I think we are past the cf-mysql-release migrations to pxc-release at this point and we will not be supporting this utility in pxc-release/1.0 and beyond based on Percona XtraDB Cluster 8.0+.
